#!/usr/bin/env node

const path = require('path');
const util = require('./out/util');

// Make sure we got a filename on the command line.
if (process.argv.length < 3) {
    console.log('Usage: node ' + process.argv[1] + ' <task>.task.md [<output>.(html|pdf|tex)]');
    process.exit(1);
}

const fileIn = process.argv[2];
const outSpec = process.argv[3] || "";

let formatOut;
let fileOut;

if (outSpec === "" || outSpec.indexOf(".") === -1) {
    // interpret as file format with default to HTML
    formatOut = outSpec;
    if (!formatOut) {
        formatOut = "html";
    }

    fileOut = util.siblingWithExtension('.' + formatOut, fileIn);

} else {
    // extract format from filename 

    fileOut = outSpec;
    formatOut = path.extname(fileOut);

    if (formatOut.startsWith(".")) {
        formatOut = formatOut.slice(1);
    }

    if (formatOut.length === 0) {
        formatOut = "html";
    }

}

formatOut = formatOut.toLowerCase();

require('./out/md2' + formatOut).runTerminal(fileIn, fileOut);
