#!/bin/bash

parent=$(dirname "$0")
cmd="$1"
shift
cmd_args="$@"


function call {
    cmd="$1"
    shift
    "$parent/bebras-$cmd" "$@"
}

if   [[ "$cmd" == q || "$cmd" == query   ]]; then
    call query "$@"
elif [[ "$cmd" == c || "$cmd" == convert ]]; then
    call convert "$@"
elif [[ "$cmd" == k || "$cmd" == check   ]]; then
    call check "$@"
else
    echo "Usage: $0 <cmd> <options...>"
    echo "where <cmd> is one of:"
    echo "      q | query"
    echo "      c | convert"
    echo "      k | check"
    exit 1
fi
