import { util } from "./main"
import { Dict } from "./util"


// ISO 3166-1 for country codes; country names slightly normalized;
// also using UK instead of GB as is done in the community
export const countryNameByCountryCodes: Dict<string> = {
	"AF": "Afghanistan",
	"AX": "Åland Islands",
	"AL": "Albania",
	"DZ": "Algeria",
	"AS": "American Samoa",
	"AD": "Andorra",
	"AO": "Angola",
	"AI": "Anguilla",
	"AQ": "Antarctica",
	"AG": "Antigua and Barbuda",
	"AR": "Argentina",
	"AM": "Armenia",
	"AW": "Aruba",
	"AU": "Australia",
	"AT": "Austria",
	"AZ": "Azerbaijan",
	"BS": "Bahamas",
	"BH": "Bahrain",
	"BD": "Bangladesh",
	"BB": "Barbados",
	"BY": "Belarus",
	"BE": "Belgium",
	"BZ": "Belize",
	"BJ": "Benin",
	"BM": "Bermuda",
	"BT": "Bhutan",
	"BO": "Bolivia",
	"BQ": "Bonaire, Sint Eustatius and Saba",
	"BA": "Bosnia and Herzegovina",
	"BW": "Botswana",
	"BV": "Bouvet Island",
	"BR": "Brazil",
	"IO": "British Indian Ocean Territory",
	"BN": "Brunei Darussalam",
	"BG": "Bulgaria",
	"BF": "Burkina Faso",
	"BI": "Burundi",
	"CV": "Cabo Verde",
	"KH": "Cambodia",
	"CM": "Cameroon",
	"CA": "Canada",
	"KY": "Cayman Islands",
	"CF": "Central African Republic",
	"TD": "Chad",
	"CL": "Chile",
	"CN": "China",
	"CX": "Christmas Island",
	"CC": "Cocos (Keeling) Islands",
	"CO": "Colombia",
	"KM": "Comoros",
	"CG": "Congo",
	"CD": "Democratic Republic of the Congo",
	"CK": "Cook Islands",
	"CR": "Costa Rica",
	"CI": "Côte d'Ivoire",
	"HR": "Croatia",
	"CU": "Cuba",
	"CW": "Curaçao",
	"CY": "Cyprus",
	"CZ": "Czech Republic",
	"DK": "Denmark",
	"DJ": "Djibouti",
	"DM": "Dominica",
	"DO": "Dominican Republic",
	"EC": "Ecuador",
	"EG": "Egypt",
	"SV": "El Salvador",
	"GQ": "Equatorial Guinea",
	"ER": "Eritrea",
	"EE": "Estonia",
	"SZ": "Eswatini",
	"ET": "Ethiopia",
	"FK": "Falkland Islands",
	"FO": "Faroe Islands",
	"FJ": "Fiji",
	"FI": "Finland",
	"FR": "France",
	"GF": "French Guiana",
	"PF": "French Polynesia",
	"TF": "French Southern Territories",
	"GA": "Gabon",
	"GM": "Gambia",
	"GE": "Georgia",
	"DE": "Germany",
	"GH": "Ghana",
	"GI": "Gibraltar",
	"GR": "Greece",
	"GL": "Greenland",
	"GD": "Grenada",
	"GP": "Guadeloupe",
	"GU": "Guam",
	"GT": "Guatemala",
	"GG": "Guernsey",
	"GN": "Guinea",
	"GW": "Guinea-Bissau",
	"GY": "Guyana",
	"HT": "Haiti",
	"HM": "Heard Island and McDonald Islands",
	"VA": "Holy See",
	"HN": "Honduras",
	"HK": "Hong Kong",
	"HU": "Hungary",
	"IS": "Iceland",
	"IN": "India",
	"ID": "Indonesia",
	"IR": "Iran",
	"IQ": "Iraq",
	"IE": "Ireland",
	"IM": "Isle of Man",
	"IL": "Israel",
	"IT": "Italy",
	"JM": "Jamaica",
	"JP": "Japan",
	"JE": "Jersey",
	"JO": "Jordan",
	"KZ": "Kazakhstan",
	"KE": "Kenya",
	"KI": "Kiribati",
	"KP": "North Korea",
	"KR": "South Korea",
	"KW": "Kuwait",
	"KG": "Kyrgyzstan",
	"LA": "Laos",
	"LV": "Latvia",
	"LB": "Lebanon",
	"LS": "Lesotho",
	"LR": "Liberia",
	"LY": "Libya",
	"LI": "Liechtenstein",
	"LT": "Lithuania",
	"LU": "Luxembourg",
	"MO": "Macao",
	"MG": "Madagascar",
	"MW": "Malawi",
	"MY": "Malaysia",
	"MV": "Maldives",
	"ML": "Mali",
	"MT": "Malta",
	"MH": "Marshall Islands",
	"MQ": "Martinique",
	"MR": "Mauritania",
	"MU": "Mauritius",
	"YT": "Mayotte",
	"MX": "Mexico",
	"FM": "Micronesia",
	"MD": "Moldova",
	"MC": "Monaco",
	"MN": "Mongolia",
	"ME": "Montenegro",
	"MS": "Montserrat",
	"MA": "Morocco",
	"MZ": "Mozambique",
	"MM": "Myanmar",
	"NA": "Namibia",
	"NR": "Nauru",
	"NP": "Nepal",
	"NL": "Netherlands",
	"NC": "New Caledonia",
	"NZ": "New Zealand",
	"NI": "Nicaragua",
	"NE": "Niger",
	"NG": "Nigeria",
	"NU": "Niue",
	"NF": "Norfolk Island",
	"MK": "North Macedonia",
	"MP": "Northern Mariana Islands",
	"NO": "Norway",
	"OM": "Oman",
	"PK": "Pakistan",
	"PW": "Palau",
	"PS": "Palestine",
	"PA": "Panama",
	"PG": "Papua New Guinea",
	"PY": "Paraguay",
	"PE": "Peru",
	"PH": "Philippines",
	"PN": "Pitcairn",
	"PL": "Poland",
	"PT": "Portugal",
	"PR": "Puerto Rico",
	"QA": "Qatar",
	"RE": "Réunion",
	"RO": "Romania",
	"RU": "Russia",
	"RW": "Rwanda",
	"BL": "Saint Barthélemy",
	"SH": "Saint Helena, Ascension and Tristan da Cunha",
	"KN": "Saint Kitts and Nevis",
	"LC": "Saint Lucia",
	"MF": "Saint Martin",
	"PM": "Saint Pierre and Miquelon",
	"VC": "Saint Vincent and the Grenadines",
	"WS": "Samoa",
	"SM": "San Marino",
	"ST": "Sao Tome and Principe",
	"SA": "Saudi Arabia",
	"SN": "Senegal",
	"RS": "Serbia",
	"SC": "Seychelles",
	"SL": "Sierra Leone",
	"SG": "Singapore",
	"SX": "Sint Maarten",
	"SK": "Slovakia",
	"SI": "Slovenia",
	"SB": "Solomon Islands",
	"SO": "Somalia",
	"ZA": "South Africa",
	"GS": "South Georgia and the South Sandwich Islands",
	"SS": "South Sudan",
	"ES": "Spain",
	"LK": "Sri Lanka",
	"SD": "Sudan",
	"SR": "Suriname",
	"SJ": "Svalbard and Jan Mayen",
	"SE": "Sweden",
	"CH": "Switzerland",
	"SY": "Syrian Arab Republic",
	"TW": "Taiwan",
	"TJ": "Tajikistan",
	"TZ": "Tanzania",
	"TH": "Thailand",
	"TL": "Timor-Leste",
	"TG": "Togo",
	"TK": "Tokelau",
	"TO": "Tonga",
	"TT": "Trinidad and Tobago",
	"TN": "Tunisia",
	"TR": "Turkey",
	"TM": "Turkmenistan",
	"TC": "Turks and Caicos Islands",
	"TV": "Tuvalu",
	"UG": "Uganda",
	"UA": "Ukraine",
	"AE": "United Arab Emirates",
	"GB": "United Kingdom",
	"UK": "United Kingdom",
	"US": "USA",
	"UM": "United States Minor Outlying Islands",
	"UY": "Uruguay",
	"UZ": "Uzbekistan",
	"VU": "Vanuatu",
	"VE": "Venezuela",
	"VN": "Vietnam",
	"VG": "Virgin Islands (British)",
	"VI": "Virgin Islands (US)",
	"WF": "Wallis and Futuna",
	"EH": "Western Sahara",
	"YE": "Yemen",
	"ZM": "Zambia",
	"ZW": "Zimbabwe",
}

export const countryCodeByCountryName: Dict<string> = {}

for (const countryCode of Object.keys(countryNameByCountryCodes)) {
	const countryName = countryNameByCountryCodes[countryCode]!
	countryCodeByCountryName[countryName] = countryCode
}

// ISO 639 Set 2/T to [ISO Language Name, ISO 639 Set 1]
export const languageNameAndShortCodeByLongCode: Dict<[string, string]> = {
	"abk": ["Abkhazian", "ab"],
	"aar": ["Afar", "aa"],
	"afr": ["Afrikaans", "af"],
	"aka": ["Akan", "ak"],
	"sqi": ["Albanian", "sq"],
	"amh": ["Amharic", "am"],
	"ara": ["Arabic", "ar"],
	"arg": ["Aragonese", "an"],
	"hye": ["Armenian", "hy"],
	"asm": ["Assamese", "as"],
	"ava": ["Avaric", "av"],
	"ave": ["Avestan", "ae"],
	"aym": ["Aymara", "ay"],
	"aze": ["Azerbaijani", "az"],
	"bam": ["Bambara", "bm"],
	"bak": ["Bashkir", "ba"],
	"eus": ["Basque", "eu"],
	"bel": ["Belarusian", "be"],
	"ben": ["Bengali", "bn"],
	"bis": ["Bislama", "bi"],
	"bos": ["Bosnian", "bs"],
	"bre": ["Breton", "br"],
	"bul": ["Bulgarian", "bg"],
	"mya": ["Burmese", "my"],
	"cat": ["Catalan, Valencian", "ca"],
	"cha": ["Chamorro", "ch"],
	"che": ["Chechen", "ce"],
	"nya": ["Chichewa, Chewa, Nyanja", "ny"],
	"zho": ["Chinese", "zh"],
	"chu": ["Church Slavonic, Old Slavonic, Old Church Slavonic", "cu"],
	"chv": ["Chuvash", "cv"],
	"cor": ["Cornish", "kw"],
	"cos": ["Corsican", "co"],
	"cre": ["Cree", "cr"],
	"hrv": ["Croatian", "hr"],
	"ces": ["Czech", "cs"],
	"dan": ["Danish", "da"],
	"div": ["Divehi, Dhivehi, Maldivian", "dv"],
	"nld": ["Dutch, Flemish", "nl"],
	"dzo": ["Dzongkha", "dz"],
	"eng": ["English", "en"],
	"epo": ["Esperanto", "eo"],
	"est": ["Estonian", "et"],
	"ewe": ["Ewe", "ee"],
	"fao": ["Faroese", "fo"],
	"fij": ["Fijian", "fj"],
	"fin": ["Finnish", "fi"],
	"fra": ["French", "fr"],
	"fry": ["Western Frisian", "fy"],
	"ful": ["Fulah", "ff"],
	"gla": ["Gaelic, Scottish Gaelic", "gd"],
	"glg": ["Galician", "gl"],
	"lug": ["Ganda", "lg"],
	"kat": ["Georgian", "ka"],
	"deu": ["German", "de"],
	"ell": ["Greek, Modern (1453–)", "el"],
	"kal": ["Kalaallisut, Greenlandic", "kl"],
	"grn": ["Guarani", "gn"],
	"guj": ["Gujarati", "gu"],
	"hat": ["Haitian, Haitian Creole", "ht"],
	"hau": ["Hausa", "ha"],
	"heb": ["Hebrew", "he"],
	"her": ["Herero", "hz"],
	"hin": ["Hindi", "hi"],
	"hmo": ["Hiri Motu", "ho"],
	"hun": ["Hungarian", "hu"],
	"isl": ["Icelandic", "is"],
	"ido": ["Ido", "io"],
	"ibo": ["Igbo", "ig"],
	"ind": ["Indonesian", "id"],
	"ina": ["Interlingua (International Auxiliary Language Association)", "ia"],
	"ile": ["Interlingue, Occidental", "ie"],
	"iku": ["Inuktitut", "iu"],
	"ipk": ["Inupiaq", "ik"],
	"gle": ["Irish", "ga"],
	"ita": ["Italian", "it"],
	"jpn": ["Japanese", "ja"],
	"jav": ["Javanese", "jv"],
	"kan": ["Kannada", "kn"],
	"kau": ["Kanuri", "kr"],
	"kas": ["Kashmiri", "ks"],
	"kaz": ["Kazakh", "kk"],
	"khm": ["Central Khmer", "km"],
	"kik": ["Kikuyu, Gikuyu", "ki"],
	"kin": ["Kinyarwanda", "rw"],
	"kir": ["Kirghiz, Kyrgyz", "ky"],
	"kom": ["Komi", "kv"],
	"kon": ["Kongo", "kg"],
	"kor": ["Korean", "ko"],
	"kua": ["Kuanyama, Kwanyama", "kj"],
	"kur": ["Kurdish", "ku"],
	"lao": ["Lao", "lo"],
	"lat": ["Latin", "la"],
	"lav": ["Latvian", "lv"],
	"lim": ["Limburgan, Limburger, Limburgish", "li"],
	"lin": ["Lingala", "ln"],
	"lit": ["Lithuanian", "lt"],
	"lub": ["Luba-Katanga", "lu"],
	"ltz": ["Luxembourgish, Letzeburgesch", "lb"],
	"mkd": ["Macedonian", "mk"],
	"mlg": ["Malagasy", "mg"],
	"msa": ["Malay", "ms"],
	"mal": ["Malayalam", "ml"],
	"mlt": ["Maltese", "mt"],
	"glv": ["Manx", "gv"],
	"mri": ["Maori", "mi"],
	"mar": ["Marathi", "mr"],
	"mah": ["Marshallese", "mh"],
	"mon": ["Mongolian", "mn"],
	"nau": ["Nauru", "na"],
	"nav": ["Navajo, Navaho", "nv"],
	"nde": ["North Ndebele", "nd"],
	"nbl": ["South Ndebele", "nr"],
	"ndo": ["Ndonga", "ng"],
	"nep": ["Nepali", "ne"],
	"nor": ["Norwegian", "no"],
	"nob": ["Norwegian Bokmål", "nb"],
	"nno": ["Norwegian Nynorsk", "nn"],
	"oci": ["Occitan", "oc"],
	"oji": ["Ojibwa", "oj"],
	"ori": ["Oriya", "or"],
	"orm": ["Oromo", "om"],
	"oss": ["Ossetian, Ossetic", "os"],
	"pli": ["Pali", "pi"],
	"pus": ["Pashto, Pushto", "ps"],
	"fas": ["Persian", "fa"],
	"pol": ["Polish", "pl"],
	"por": ["Portuguese", "pt"],
	"pan": ["Punjabi, Panjabi", "pa"],
	"que": ["Quechua", "qu"],
	"ron": ["Romanian, Moldavian, Moldovan", "ro"],
	"roh": ["Romansh", "rm"],
	"run": ["Rundi", "rn"],
	"rus": ["Russian", "ru"],
	"sme": ["Northern Sami", "se"],
	"smo": ["Samoan", "sm"],
	"sag": ["Sango", "sg"],
	"san": ["Sanskrit", "sa"],
	"srd": ["Sardinian", "sc"],
	"srp": ["Serbian", "sr"],
	"sna": ["Shona", "sn"],
	"snd": ["Sindhi", "sd"],
	"sin": ["Sinhala, Sinhalese", "si"],
	"slk": ["Slovak", "sk"],
	"slv": ["Slovenian", "sl"],
	"som": ["Somali", "so"],
	"sot": ["Southern Sotho", "st"],
	"spa": ["Spanish, Castilian", "es"],
	"sun": ["Sundanese", "su"],
	"swa": ["Swahili", "sw"],
	"ssw": ["Swati", "ss"],
	"swe": ["Swedish", "sv"],
	"tgl": ["Tagalog", "tl"],
	"tah": ["Tahitian", "ty"],
	"tgk": ["Tajik", "tg"],
	"tam": ["Tamil", "ta"],
	"tat": ["Tatar", "tt"],
	"tel": ["Telugu", "te"],
	"tha": ["Thai", "th"],
	"bod": ["Tibetan", "bo"],
	"tir": ["Tigrinya", "ti"],
	"ton": ["Tonga (Tonga Islands)", "to"],
	"tso": ["Tsonga", "ts"],
	"tsn": ["Tswana", "tn"],
	"tur": ["Turkish", "tr"],
	"tuk": ["Turkmen", "tk"],
	"twi": ["Twi", "tw"],
	"uig": ["Uighur, Uyghur", "ug"],
	"ukr": ["Ukrainian", "uk"],
	"urd": ["Urdu", "ur"],
	"uzb": ["Uzbek", "uz"],
	"ven": ["Venda", "ve"],
	"vie": ["Vietnamese", "vi"],
	"vol": ["Volapük", "vo"],
	"wln": ["Walloon", "wa"],
	"cym": ["Welsh", "cy"],
	"wol": ["Wolof", "wo"],
	"xho": ["Xhosa", "xh"],
	"iii": ["Sichuan Yi, Nuosu", "ii"],
	"yid": ["Yiddish", "yi"],
	"yor": ["Yoruba", "yo"],
	"zha": ["Zhuang, Chuang", "za"],
	"zul": ["Zulu", "zu"],
}

export function defaultLanguageCode(): string {
	return "eng"
}

export const languageLongCodeByLanguageName: Dict<string> = {}

for (const langCode of Object.keys(languageNameAndShortCodeByLongCode)) {
	const langName = languageNameAndShortCodeByLongCode[langCode]![0]
	languageLongCodeByLanguageName[langName] = langCode
}

export function countrySuggestionsFor(country: string): string[] {
	return replacementSuggestionsFor(country, countryNameByCountryCodes, s => s, 3)
}

export function languageSuggestionsFor(lang: string): string[] {
	return replacementSuggestionsFor(lang, languageNameAndShortCodeByLongCode, t => t[0], 2)
}

function replacementSuggestionsFor<T>(item: string, validValueSource: Dict<T>, get: (value: T) => string, maxDist: number) {
	const sugg = [] as string[]
	for (const _e of Object.values(validValueSource)) {
		const e = get(_e!)
		const dist = util.levenshteinDistance(item, e)
		if (dist <= maxDist) {
			sugg.push(e)
		}
	}
	return sugg
}
